### ISSUE TITLE
ApplicationLauncher icon flickers on/off repeatedly

### ISSUE THREAD

**Issue by tivec** [WaveFunctionP/ForScience#4]
On KSP 1.1.2, the app launcher icon keeps blinking. It doesn't seem to go from green to red, but rather green to removed, then readded. Debug spam confirms:

```[LOG 07:36:37.295] ScaleModList: listSize 861 maxListSize 674```

This line is called whenever a button is added/removed, and with ForScience installed it happens every update.

**Comment by WaveFunctionP** [comment]
Have you updated to 1.4?

**Comment by tivec** [comment]
Well *that* could explain why I couldn't see any correlation between your code and what was happening. I'll give it a try later today and see if it solved the issue.

**Comment by WaveFunctionP** [comment]
I assume that the issue is resolved then?

**Comment by tivec** [comment]
I haven't had a chance to check, but I can reopen if it is still an issue in the later version.
